# -*- coding: utf-8 -*-
"""car_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gd1Ru0XEvIpXUmEWlxlFRxBce5xCP0vq
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("1776311302-P3-Car Market Trends Analysis with Car Dekho Data (2).csv")

print(df.head())

plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x="Present_Price", y="Selling_Price")

plt.title("Present Price vs Selling Price")
plt.xlabel("Present Price")
plt.ylabel("Selling Price")
plt.show()

fuel_price = df.groupby("Fuel_Type")["Selling_Price"].mean()

plt.figure(figsize=(8,6))
sns.barplot(x=fuel_price.index, y=fuel_price.values)

plt.title("Average Selling Price by Fuel Type")
plt.xlabel("Fuel Type")
plt.ylabel("Average Selling Price")
plt.show()

sell_price=df.groupby("Seller_Type")["Selling_Price"].mean()
plt.figure(figsize=(8,6))
sns.barplot(x=sell_price.index, y=sell_price.values)

plt.title("Average Selling Price by Seller Type")
plt.xlabel("Seller Type")
plt.ylabel("Average Selling Price")

transmission_price=df.groupby("Transmission")["Selling_Price"].mean()
plt.figure(figsize=(8,6))
sns.barplot(x=transmission_price.index, y=transmission_price.values)

plt.title("Average Selling Price by Transmission Type")
plt.xlabel("Transmission Type")
plt.ylabel("Average Selling Price")

year_price = df.groupby("Year")["Selling_Price"].mean()

plt.figure(figsize=(9,5))

sns.lineplot(
    x=year_price.index,
    y=year_price.values,
    marker="o"
)

plt.title("Average Selling Price by Manufacturing Year")
plt.xlabel("Manufacturing Year")
plt.ylabel("Average Selling Price")


plt.show()